# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[(1, 'Hardcover'), (2, 'Paperback'), (3, 'E-book')], max_length=120),
        ),
    ]
